# Project information
site_name: SFI5774
site_description: Complemento _online_ às aulas da disciplina de Mecânica Quântica Aplicada do IFSC/USP 
site_author: Sérgio R. Muniz @IFSC/USP
site_url: https://srmuniz.github.io/sfi5774/

# Repository
repo_name: sfi5774/Aulas/
repo_url: https://srmuniz.github.io/sfi5774

# Copyright
copyright: Copyright &copy; 2020  Sérgio R. Muniz  (CC-BY-NC-SA)

# Configuration
theme:
  name: material  #cinder
  language: pt
  palette:
    primary: indigo
    accent: indigo
  font:
    #text: Ubuntu
    text: Roboto
    code: Roboto Mono

# Navigation
nav:
    - Home: index.md
    - Aulas S5 & S6: Aulas_S5-S6.md 
    - Aulas S7: Aulas_S7.md
    - Aula 13 - Lab 1: Aula13_Lab1.md
    - Aula 14 - Lab 2: Aula14_Lab2.md
    - Aula 15: Aula15.md
    - About: about.md

# Extensions
markdown_extensions:
  - admonition
  - footnotes 
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  #- pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  #- pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  #- pymdownx.tasklist:
  #    custom_checkbox: true
  #- pymdownx.tabbed
  #- pymdownx.tilde

plugins:
  - search:
      lang:
        - pt
        #- en
  - git-revision-date-localized

extra_javascript:
#  - ./load-mathjax.js
#  - load-mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_SVG
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=AM_SVG
#  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/MathJax.js?config=TeX-MML-AM_CHTML
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
